name: BuildEnv Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout-repo
        uses: actions/checkout@v3

      - name: calculate-golang-version
        working-directory: server/
        id: go
        run: echo GO_VERSION=$(cat .go-version) >> "$GITHUB_ENV"

      - name: update-ubuntu
        run: sudo apt-get update -y

      - name: setup-go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      
      - name: build-client
        working-directory: webapp/
        run: |
          make clean
          make package

      - name: build-server
        working-directory: server/
        run: |
          make setup-go-work;
          make build-linux
          make package-linux

      - name: upload-binaries
        uses: actions/upload-artifact@v3
        with:
          name: mattermost-team-linux-amd64.tar.gz
          path: server/dist/mattermost-team-linux-amd64.tar.gz
          
      - name: move-binaries
        run: |
          mv server/dist/mattermost-team-linux-amd64.tar.gz server/build/mattermost-team-linux-amd64.tar.gz

      - name: docker-login
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: read-docker-image-identifiers
        run: echo "IMAGE_REPOSITORY=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: build-and-push
        uses: docker/build-push-action@v6.7.0
        with:
          provenance: false
          context: server/build
          push: true
          pull: true
          tags: ghcr.io/${{ env.IMAGE_REPOSITORY }}/mattermost-build-server:latest
