name: BuildEnv Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-image:
    runs-on: ubuntu-22.04
    steps:
      - name: buildenv/checkout-repo
        uses: actions/checkout@v4.1.7

      - name: buildenv/calculate-golang-version
        working-directory: server/
        id: go
        run: echo GO_VERSION=$(cat .go-version) >> "${GITHUB_OUTPUT}"

      - name: buildenv/docker-login
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: read-docker-image-identifiers
        name: Read Docker Image Identifiers
        run: echo "IMAGE_REPOSITORY=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: buildenv/build-and-push
        uses: docker/build-push-action@v6.7.0
        with:
          provenance: false
          file: server/build/Dockerfile.buildenv
          push: true
          pull: true
          tags: ghcr.io/${{ env.IMAGE_REPOSITORY }}/mattermost-build-server:${{ steps.go.outputs.GO_VERSION }}
