name: BuildEnv Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: buildenv/checkout-repo
        uses: actions/checkout@v3

      - name: buildenv/calculate-golang-version
        working-directory: server/
        id: go
        run: echo GO_VERSION=$(cat .go-version) >> "$GITHUB_ENV"

      - name: buildenv/setup-go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      
      - name: buildenv/build-client
        working-directory: webapp/
        run: |
          make clean
          make package

      - name: buildenv/build-server
        working-directory: server/
        run: |
          make setup-go-work;
          make build-linux
          make package-linux

      - name: buildenv/upload-binaries
        uses: actions/upload-artifact@v3
        with:
          name: mattermost-team-linux-arm64.tar.gz
          path: server/dist/mattermost-team-linux-arm64.tar.gz

  build-image:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: buildenv/checkout-repo
        uses: actions/checkout@v4.1.7

      - name: buildenv/calculate-golang-version
        working-directory: server/
        id: go
        run: echo GO_VERSION=$(cat .go-version) >> "${GITHUB_OUTPUT}"

      - name: buildenv/download-binaries
        uses: actions/download-artifact@v4.1.8
        with:
          path: server/build/
      
      - name: buildenv/unzip-binaries
        run: unzip server/build/mattermost-team-linux-arm64.tar.gz.zip -d server/build/

      - name: buildenv/docker-login
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: read-docker-image-identifiers
        name: Read Docker Image Identifiers
        run: echo "IMAGE_REPOSITORY=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: buildenv/build-and-push
        uses: docker/build-push-action@v6.7.0
        with:
          provenance: false
          file: server/build/Dockerfile
          push: true
          pull: true
          tags: ghcr.io/${{ env.IMAGE_REPOSITORY }}/mattermost-build-server:${{ steps.go.outputs.GO_VERSION }}
